api:
  build: ./api/
  dockerfile: ./Dockerfile
  ports:
   - "8080:80"
  volumes:
   - ./api/:/var/www

front:
  build: ./front-categorias/
  dockerfile: ./Dockerfile
  command: "ng serve --host 0.0.0.0 --poll=50"
  ports:
    - "4200:4200" 
    - "49153:49153"
  expose:
    - "4200" 
    - "49153"
  volumes:
    - ./front-categorias/:/opt/app/
